[versions]
agp = "7.4.0-rc03"
kotlin = "1.8.0"
tree-sitter = "1.0.10"
editor = "0.20.4"
glide = "4.14.2"
androidx-vectordrawable = "1.1.0"
androidx-navigation = "2.5.3"
ksp = "1.8.0-1.0.8"
antlr4 = "4.11.1"

[libraries]

# AndroidIDE
androidide-javac = { module = "io.github.itsaky:nb-javac-android", version = "17.0.0.4-SNAPSHOT" }
androidide-ts = { module = "io.github.itsaky:android-tree-sitter", version.ref = "tree-sitter" }
androidide-ts-java = { module = "io.github.itsaky:tree-sitter-java", version.ref = "tree-sitter" }
androidide-ts-xml = { module = "io.github.itsaky:tree-sitter-xml", version.ref = "tree-sitter" }

# Common
common-editor = { module = "io.github.Rosemoe.sora-editor:editor", version.ref = "editor" }
common-editor-ts = { module = "io.github.Rosemoe.sora-editor:language-treesitter", version.ref = "editor" }
common-utilcode = { module = "com.blankj:utilcodex", version = "1.31.1" }
common-glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
common-glide_ap = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
common-jsoup = { module = "org.jsoup:jsoup", version = "1.15.3" }
common-antlr4 = { module = "org.antlr:antlr4", version.ref = "antlr4" }
common-antlr4-runtime = { module = "org.antlr:antlr4-runtime", version.ref = "antlr4" }
common-javaparser = { module = "com.github.javaparser:javaparser-symbol-solver-core", version = "3.24.10" }
common-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.12.0" }
common-io = { module = "commons-io:commons-io", version = "2.11.0" }
common-kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-jkotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
common-eventbus_ap = { module = "org.greenrobot:eventbus-annotation-processor", version = "3.3.1" }
common-javapoet = { module = "com.squareup:javapoet", version = "1.13.0" }
common-ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
common-jsonrpc = { module = "org.eclipse.lsp4j:org.eclipse.lsp4j.jsonrpc", version = "0.19.0" }

# AndroidX
androidx-annotation = { module = "androidx.annotation:annotation", version = "1.5.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-cardview = { module = "androidx.cardview:cardview", version = "1.0.0" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version = "1.2.0" }
androidx-drawer = { module = "androidx.drawerlayout:drawerlayout", version = "1.1.1" }
androidx-grid = { module = "androidx.gridlayout:gridlayout", version = "1.0.0" }
androidx-preference = { module = "androidx.preference:preference", version = "1.2.0" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.2.1" }
androidx-vectors = { module = "androidx.vectordrawable:vectordrawable", version.ref = "androidx-vectordrawable" }
androidx-animated_vectors = { module = "androidx.vectordrawable:vectordrawable-animated", version.ref = "androidx-vectordrawable" }
androidx-ktx = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-fragment_ktx = { module = "androidx.fragment:fragment-ktx", version = "1.5.5" }
androidx-lib_desugaring = { module = "com.android.tools:desugar_jdk_libs", version = "1.1.6" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.0" }
androidx-nav_frag = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-nav_ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-nav_dynamic_features = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "androidx-navigation" }

# Google
google-material = { module = "com.google.android.material:material", version = "1.7.0" }
google-gson = { module = "com.google.code.gson:gson", version = "2.10.1" }
google-guava = { module = "com.google.guava:guava", version = "31.1-android" }
google-guava-jre = { module = "com.google.guava:guava", version = "31.1-jre" }
google-auto-value-annotations = { module = "com.google.auto.value:auto-value-annotations", version = "1.10.1" }
google-auto-value-ap = { module = "com.google.auto.value:auto-value", version = "1.10.1" }
google-auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version = "1.0.1" }
google-auto-service = { module = "com.google.auto.service:auto-service", version = "1.0.1" }
google-oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version = "17.0.0" }
google-protobuf = { module = "com.google.protobuf:protobuf-java", version = "3.10.0" }
google-java-format = { module ="com.google.googlejavaformat:google-java-format", version="1.15.0" }

# AAPT2
aapt2-common = { module = "com.android.tools:common", version = "30.2.2" }
aapt2-annotations = { module = "com.android.tools:annotations", version = "30.2.2" }
aapt2-jb-annotations = { module = "org.jetbrains:annotations", version = "13.0" }
aapt2-proto = { module = "com.android.tools.build:aapt2-proto", version = "7.2.2-7984345" }

# XML
xml-xercesImpl = { module = "xerces:xercesImpl", version = "2.12.2" }
xml-apis = { module = "xml-apis:xml-apis", version = "2.0.2" }
xml-remark = { module = "com.kotcrab.remark:remark", version = "1.2.0" }
xml-resolver = { module = "xml-resolver:xml-resolver", version = "1.2" }
xml-jb-annotations = { module = "org.jetbrains:annotations", version = "23.1.0" }

# GIT
git-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version = "3.7.1.201504261725-r" }

# Tests
tests-junit = { module = "junit:junit", version = "4.13.2" }
tests-google-truth = { module = "com.google.truth:truth", version = "1.1.3" }
tests-robolectric = { module = "org.robolectric:robolectric", version = "4.9.2" }
tests-androidx-test-core = { module = "androidx.test:core", version = "1.5.0" }
tests-androidx-junit = { module = "androidx.test.ext:junit", version = "1.1.5" }
tests-androidx-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1" }
tests-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version = "4.1.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
